{
 "title": "Stock share monitoring",
 "description": "Watch the price of the stock shares you own. For more detail : https://github.com/pbrissaud/suivi-bourse-app",
 "time": { "from": "now-30d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "share",
    "label": "Share",
    "query": {
     "query": "label_values(sb_share_info{company_sector=~\"$sector\", share_market=~\"$market\", share_exchange=~\"$exchange\"},share_name)"
    }
   },
   {
    "name": "sector",
    "label": "Sector",
    "query": {
     "query": "label_values(sb_share_info, company_sector)"
    }
   },
   {
    "name": "market",
    "label": "Market",
    "query": {
     "query": "label_values(sb_share_info, share_market)"
    }
   },
   {
    "name": "exchange",
    "label": "Exchange",
    "query": {
     "query": "label_values(sb_share_info, share_exchange)"
    }
   }
  ]
 },
 "panels": [
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(sb_purchased_price{share_name=~\"$share\"} * on(share_name) sb_purchased_quantity{share_name=~\"$share\"})",
     "legendFormat": "Total Investment"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(sb_share_price{share_name=~\"$share\"} * on(share_name) sb_owned_quantity{share_name=~\"$share\"})",
     "legendFormat": "Total Valuation"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "((sum(sb_share_price{share_name=~\"$share\"} * on(share_name) sb_owned_quantity{share_name=~\"$share\"}) - sum(sb_purchased_price{share_name=~\"$share\"} * on(share_name) sb_purchased_quantity{share_name=~\"$share\"})) + sum(sb_received_dividend{share_name=~\"$share\"})) / sum(sb_purchased_price{share_name=~\"$share\"} * on(share_name) sb_purchased_quantity{share_name=~\"$share\"})",
     "legendFormat": "Total Performance"
    }
   ]
  },
  {
   "title": "$share",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "repeat": "share",
   "targets": [
    {}
   ]
  },
  {
   "title": "Share price evolution",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "targets": [
    {
     "expr": "last_over_time(sb_share_price{share_name=\"$share\"}[$__rate_interval])",
     "legendFormat": "{{share_name}}"
    }
   ]
  },
  {
   "title": "Purchased quantity",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sb_purchased_quantity{share_name=\"$share\"}"
    }
   ]
  },
  {
   "title": "Cost price",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sb_purchased_price{share_name=\"$share\"}"
    }
   ]
  },
  {
   "title": "Fees",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sb_purchased_fee{share_name=\"$share\"}"
    }
   ]
  },
  {
   "title": "Actual price",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sb_share_price{share_name=\"$share\"}"
    }
   ]
  },
  {
   "title": "Unitary Gain / Loss ",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sb_share_price{share_name=\"$share\"} - sb_purchased_price{share_name=\"$share\"}"
    }
   ]
  },
  {
   "title": "Owned quantity",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sb_owned_quantity{share_name=\"$share\"}"
    }
   ]
  },
  {
   "title": "Received dividend",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sb_received_dividend{share_name=\"$share\"}"
    }
   ]
  },
  {
   "title": "Total gain / loss",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "((sb_owned_quantity{share_name=\"$share\"} * sb_share_price{share_name=\"$share\"}) + sb_received_dividend{share_name=\"$share\"}) - ((sb_purchased_quantity{share_name=\"$share\"} * sb_purchased_price{share_name=\"$share\"}) + sb_purchased_fee{share_name=\"$share\"})"
    }
   ]
  }
 ]
}